<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/3_3_Concise_Implementation_of_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch
import d2l as d2l
from torch.utils import data

In [2]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):
  dataset = data.TensorDataset(*data_arrays)
  return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [4]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [5]:
next(iter(data_iter))

[tensor([[-2.1070,  0.0842],
         [ 1.2037, -1.7373],
         [-1.2129,  1.2884],
         [ 0.9777, -0.6063],
         [-0.1287,  0.2194],
         [ 0.1732,  0.7142],
         [-0.0203,  0.8120],
         [-0.0678, -0.3585],
         [ 0.0869, -1.4852],
         [ 0.2062, -1.2542]]), tensor([[-0.3144],
         [12.5073],
         [-2.6067],
         [ 8.2288],
         [ 3.1928],
         [ 2.1075],
         [ 1.4048],
         [ 5.2823],
         [ 9.4234],
         [ 8.8732]])]

In [6]:
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [9]:
print(net[0])
net[0].weight.data.normal_(0, 0.01)
print(net[0].weight.data.normal_(0, 0.01))
net[0].bias.data.fill_(0)
print(net[0].bias.data.fill_(0))

Linear(in_features=2, out_features=1, bias=True)
tensor([[-0.0072, -0.0033]])
tensor([0.])


In [10]:
loss = nn.MSELoss()

In [19]:
for p in iter(net.parameters()):
  print(p)

trainer = torch.optim.SGD(net.parameters(), lr=0.03)
print(trainer)

Parameter containing:
tensor([[-0.0072, -0.0033]], requires_grad=True)
Parameter containing:
tensor([0.], requires_grad=True)
SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [21]:
num_epochs = 3
for epoch in range(num_epochs):
  for X, y in data_iter:
    l = loss(net(X), y)
    trainer.zero_grad()
    # print("l: " + str(l))
    l.backward()
    trainer.step()
  l = loss(net(features), labels)
  print(f'epoch {epoch + 1}, loss{l:f}')

epoch 1, loss0.000102
epoch 2, loss0.000103
epoch 3, loss0.000102


In [24]:
w = net[0].weight.data
print('w的估计误差: ' , true_w - w.reshape(true_w.shape))
b = net[0].bias.data
print('b的估计误差: ' , true_b-b)

w的估计误差:  tensor([0.0002, 0.0003])
b的估计误差:  tensor([0.0001])
