<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/4_6_Dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import d2l
import torch
from torch import nn

In [45]:
def dropout_layer(X, dropout):
  assert 0 <= dropout <= 1

  if dropout == 1:
    return torch.zeros_like(X)
  if dropout == 0:
    return X
  
  print("Dropout: ", dropout)
  # print(torch.Tensor(X.shape))
  mask_1 = torch.Tensor(X.shape).uniform_(0,1)
  print(mask_1)
  mask_2 = mask_1 > dropout
  print(mask_2)
  mask = mask_2.float()
  print(mask)
  print(mask * X)
  return mask * X / (1.0-dropout)

In [46]:
X = torch.arange(16, dtype=torch.float32).reshape((2,8))
print(X)
# print(dropout_layer(X, 0))
# print(dropout_layer(X, 1))
print(dropout_layer(X, 0.5))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
Dropout:  0.5
tensor([[0.2568, 0.4757, 0.8253, 0.1560, 0.4816, 0.5090, 0.4377, 0.5393],
        [0.0881, 0.1369, 0.0994, 0.8727, 0.6693, 0.2812, 0.8410, 0.7119]])
tensor([[False, False,  True, False, False,  True, False,  True],
        [False, False, False,  True,  True, False,  True,  True]])
tensor([[0., 0., 1., 0., 0., 1., 0., 1.],
        [0., 0., 0., 1., 1., 0., 1., 1.]])
tensor([[ 0.,  0.,  2.,  0.,  0.,  5.,  0.,  7.],
        [ 0.,  0.,  0., 11., 12.,  0., 14., 15.]])
tensor([[ 0.,  0.,  4.,  0.,  0., 10.,  0., 14.],
        [ 0.,  0.,  0., 22., 24.,  0., 28., 30.]])
