<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/5_2_Parameter_Management.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,1))
X = torch.rand(size=(2, 4))
print("X: ", X)
net(X)

X:  tensor([[0.0173, 0.8983, 0.3944, 0.4591],
        [0.2402, 0.9538, 0.1135, 0.6584]])


tensor([[0.1469],
        [0.1187]], grad_fn=<AddmmBackward0>)

In [2]:
print(net[0].state_dict())
print(net[1].state_dict())
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.0540,  0.2937, -0.1221, -0.4427],
        [-0.0686, -0.1953, -0.0922,  0.2773],
        [ 0.0097, -0.0901,  0.3324,  0.4406],
        [-0.4664,  0.1181, -0.0505,  0.3937],
        [-0.0735, -0.2513, -0.4318, -0.4944],
        [ 0.3794,  0.0194,  0.2909,  0.0353],
        [-0.2354, -0.2390,  0.2752, -0.0767],
        [-0.3083,  0.3241,  0.0627, -0.0662]])), ('bias', tensor([-0.3465, -0.0035, -0.4239,  0.0056,  0.4406,  0.2583,  0.3502,  0.2346]))])
OrderedDict()
OrderedDict([('weight', tensor([[ 0.0019,  0.0810,  0.2812, -0.0215,  0.2483,  0.0781,  0.3060, -0.2359]])), ('bias', tensor([0.1791]))])


In [3]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.1791], requires_grad=True)
tensor([0.1791])


In [4]:
net[2].weight.grad == None

True

In [5]:
print(*[(name, param.shape) for name, param in net[0].named_parameters()])
print(*[(name, param.shape) for name, param in net.named_parameters()])

('weight', torch.Size([8, 4])) ('bias', torch.Size([8]))
('0.weight', torch.Size([8, 4])) ('0.bias', torch.Size([8])) ('2.weight', torch.Size([1, 8])) ('2.bias', torch.Size([1]))


In [6]:
net.state_dict()['2.bias'].data

tensor([0.1791])

In [7]:
def block1():
  return nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,4), nn.ReLU())

def block2():
  net = nn.Sequential()
  for i in range(4):
    net.add_module(f'block{i}', block1())
  return net

rgnet = nn.Sequential(block2(), nn.Linear(4,1))
rgnet(X)

tensor([[-0.4034],
        [-0.4035]], grad_fn=<AddmmBackward0>)

In [8]:
print(rgnet)

Sequential(
  (0): Sequential(
    (block0): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block1): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block2): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
    (block3): Sequential(
      (0): Linear(in_features=4, out_features=8, bias=True)
      (1): ReLU()
      (2): Linear(in_features=8, out_features=4, bias=True)
      (3): ReLU()
    )
  )
  (1): Linear(in_features=4, out_features=1, bias=True)
)


In [9]:
print(len(rgnet))
print(rgnet[1])
print(rgnet[0])

2
Linear(in_features=4, out_features=1, bias=True)
Sequential(
  (block0): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block1): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block2): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
  (block3): Sequential(
    (0): Linear(in_features=4, out_features=8, bias=True)
    (1): ReLU()
    (2): Linear(in_features=8, out_features=4, bias=True)
    (3): ReLU()
  )
)


In [10]:
print(rgnet[0][0])
print(rgnet[0][1])
print(rgnet[0][1][0].bias)
print(rgnet[0][1][0].bias.data)
print(rgnet[0][1][2].bias)

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
)
Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=4, bias=True)
  (3): ReLU()
)
Parameter containing:
tensor([ 0.3674,  0.1261, -0.0296,  0.3952,  0.1191,  0.1601,  0.2010,  0.1934],
       requires_grad=True)
tensor([ 0.3674,  0.1261, -0.0296,  0.3952,  0.1191,  0.1601,  0.2010,  0.1934])
Parameter containing:
tensor([-0.1920, -0.2878,  0.0794, -0.1679], requires_grad=True)


In [11]:
def init_normal(m):
  if type(m) == nn.Linear:
    nn.init.normal_(m.weight, mean=0, std=0.01)
    nn.init.zeros_(m.bias)
net.apply(init_normal)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([ 2.0366e-03, -1.3044e-02,  3.9205e-03, -6.3318e-05]), tensor(0.))

In [13]:
def init_constant(m):
  if type(m) == nn.Linear:
    nn.init.constant_(m.weight, 1)
    nn.init.zeros_(m.bias)
net.apply(init_constant)
net[0].weight.data[0], net[0].bias.data[0]

(tensor([1., 1., 1., 1.]), tensor(0.))

In [15]:
def xavier(m):
  if type(m) == nn.Linear:
    nn.init.xavier_uniform_(m.weight)
def init_42(m):
  if type(m) == nn.Linear:
    nn.init.constant_(m.weight, 42)

net[0].apply(xavier)
net[2].apply(init_42)
print(net[0].weight.data)
print(net[2].weight.data)

tensor([[ 0.2765,  0.3608,  0.0129,  0.4213],
        [-0.4318, -0.1344, -0.6114,  0.2673],
        [ 0.4529, -0.3427, -0.1170,  0.0025],
        [-0.3314,  0.2249, -0.5395, -0.5321],
        [-0.2810,  0.1532, -0.6672, -0.0863],
        [-0.2933,  0.5748, -0.2755,  0.6273],
        [-0.6250,  0.3000, -0.2182,  0.5605],
        [-0.4876, -0.2490,  0.5098,  0.2552]])
tensor([[42., 42., 42., 42., 42., 42., 42., 42.]])


In [21]:
def my_init(m):
  if type(m) == nn.Linear:
    print("Init", *[(name, param.shape) 
    for name, param in m.named_parameters()][0])
    nn.init.uniform_(m.weight, -10, 10)
    print(m.weight.data)
    print(m.weight.data.abs() >= 5)
    m.weight.data *= m.weight.data.abs() >= 5

net.apply(my_init)
net[0].weight[:2]

Init weight torch.Size([8, 4])
tensor([[ 5.9459,  0.7803, -4.9364, -0.3663],
        [-4.4939, -1.1070,  8.1198,  9.4891],
        [-8.0505, -3.2832,  5.2465,  2.0265],
        [-8.3739, -4.1209, -2.9661,  4.3884],
        [-1.3957, -2.3183,  3.4091,  7.9962],
        [-5.4786, -6.2086, -6.2904,  6.2312],
        [-9.0887, -8.4588, -1.4303,  2.6583],
        [-1.8227,  3.8300, -0.8937, -6.1169]])
tensor([[ True, False, False, False],
        [False, False,  True,  True],
        [ True, False,  True, False],
        [ True, False, False, False],
        [False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True, False, False],
        [False, False, False,  True]])
Init weight torch.Size([1, 8])
tensor([[ 5.2562,  6.2661, -1.0588,  4.0410,  2.8918,  5.8390,  7.7002, -4.5444]])
tensor([[ True,  True, False, False, False,  True,  True, False]])


tensor([[5.9459, 0.0000, -0.0000, -0.0000],
        [-0.0000, -0.0000, 8.1198, 9.4891]], grad_fn=<SliceBackward0>)

In [26]:
print(net[0].weight.data)
net[0].weight.data[:] += 1
print(net[0].weight.data)
net[0].weight.data[0,0] = 42
print(net[0].weight.data)
# net[0].weight.data[0]

tensor([[42.0000,  4.0000,  4.0000,  4.0000],
        [ 4.0000,  4.0000, 12.1198, 13.4891],
        [-4.0505,  4.0000,  9.2465,  4.0000],
        [-4.3739,  4.0000,  4.0000,  4.0000],
        [ 4.0000,  4.0000,  4.0000, 11.9962],
        [-1.4786, -2.2086, -2.2904, 10.2312],
        [-5.0887, -4.4588,  4.0000,  4.0000],
        [ 4.0000,  4.0000,  4.0000, -2.1169]])
tensor([[43.0000,  5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000, 13.1198, 14.4891],
        [-3.0505,  5.0000, 10.2465,  5.0000],
        [-3.3739,  5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000,  5.0000, 12.9962],
        [-0.4786, -1.2086, -1.2904, 11.2312],
        [-4.0887, -3.4588,  5.0000,  5.0000],
        [ 5.0000,  5.0000,  5.0000, -1.1169]])
tensor([[42.0000,  5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000, 13.1198, 14.4891],
        [-3.0505,  5.0000, 10.2465,  5.0000],
        [-3.3739,  5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000,  5.0000, 12.9962],
        [-0.4786, -1.2086, -1.29

In [32]:
shared = nn.Linear(8, 8)
net = nn.Sequential(nn.Linear(4,8), nn.ReLU(),
            shared, nn.ReLU(),
            shared, nn.ReLU(),
            nn.Linear(8,1))
net(X)
print(net)
print(net[2])
print(net[4])
print(net[2].weight)
print(net[4].weight)
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0,0] = 100
print(net[2].weight)
print(net[4].weight)
print(net[2].weight.data[0] == net[4].weight.data[0])

Sequential(
  (0): Linear(in_features=4, out_features=8, bias=True)
  (1): ReLU()
  (2): Linear(in_features=8, out_features=8, bias=True)
  (3): ReLU()
  (4): Linear(in_features=8, out_features=8, bias=True)
  (5): ReLU()
  (6): Linear(in_features=8, out_features=1, bias=True)
)
Linear(in_features=8, out_features=8, bias=True)
Linear(in_features=8, out_features=8, bias=True)
Parameter containing:
tensor([[-0.2005, -0.1997,  0.1170,  0.2676, -0.3370,  0.2046, -0.0053, -0.2817],
        [ 0.1029,  0.3076,  0.1678,  0.1794,  0.0112,  0.2799, -0.2889,  0.1704],
        [ 0.2223, -0.0932, -0.3376, -0.1725,  0.2679,  0.2549,  0.3147,  0.3504],
        [-0.1977, -0.0862,  0.0401, -0.1490,  0.0332,  0.3199, -0.1286,  0.2677],
        [-0.0233, -0.2115,  0.2500,  0.2606,  0.3462,  0.1816,  0.2042, -0.3046],
        [-0.1979, -0.1079,  0.0487,  0.0058, -0.1708, -0.1901, -0.2457,  0.3180],
        [ 0.2773, -0.3366, -0.0203,  0.1568, -0.0338, -0.2786,  0.2322,  0.3030],
        [-0.0129, -0.0405,