<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/5_3_Custom_Layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
  def __init__(self):
    super().__init__()
  
  def forward(self, X):
    print("X: ", X)
    print("X Mean: ", X.mean())
    print("X - X.Mean: ", X - X.mean())
    return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

X:  tensor([1., 2., 3., 4., 5.])
X Mean:  tensor(3.)
X - X.Mean:  tensor([-2., -1.,  0.,  1.,  2.])


tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8,2), CenteredLayer())

In [4]:
input = torch.rand(4,8)
print("Input: ", input)
Y = net(input)
Y.mean()

Input:  tensor([[0.8296, 0.8571, 0.4635, 0.5574, 0.6561, 0.2738, 0.6505, 0.1887],
        [0.1042, 0.8725, 0.2550, 0.0664, 0.9819, 0.6921, 0.0300, 0.7011],
        [0.8807, 0.3948, 0.5668, 0.8759, 0.3491, 0.8565, 0.4512, 0.2895],
        [0.2682, 0.7775, 0.4467, 0.4558, 0.6551, 0.5909, 0.8690, 0.7516]])
X:  tensor([[-0.0993, -0.0456],
        [-0.2514, -0.2652],
        [ 0.1281, -0.2533],
        [-0.2250, -0.1306]], grad_fn=<AddmmBackward0>)
X Mean:  tensor(-0.1428, grad_fn=<MeanBackward0>)
X - X.Mean:  tensor([[ 0.0435,  0.0972],
        [-0.1086, -0.1224],
        [ 0.2709, -0.1105],
        [-0.0822,  0.0122]], grad_fn=<SubBackward0>)


tensor(0., grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
  def __init__(self, in_units, units):
    super().__init__()
    self.weight = nn.Parameter(torch.randn(in_units, units))
    self.bias = nn.Parameter(torch.randn(units,))
  def forward(self, X):
    linear = torch.matmul(X, self.weight.data) + self.bias.data
    return F.relu(linear)

In [9]:
linear = MyLinear(4, 4)
linear.weight

Parameter containing:
tensor([[ 0.7459, -1.0004, -1.6140,  1.4607],
        [ 0.5132,  0.0397,  1.0140, -0.7431],
        [-0.8249,  0.9454,  0.9305, -1.1813],
        [-0.3919, -0.3526,  1.6565,  0.1892]], requires_grad=True)

In [10]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6290,  2.0412,  0.1312],
        [-0.6131, -1.1620, -0.0095],
        [ 0.7774, -1.7878,  0.2487],
        [-1.0430, -0.7168,  1.0207],
        [-1.8166,  0.8142,  0.4358]], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 1.9026],
        [0.0000, 0.0000, 1.5886]])

In [18]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[11.0841],
        [ 6.8045]])