<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/5_4_File_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')

In [5]:
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [6]:
mydict = {'x':x, 'y':y}
torch.save(mydict, 'mydict')

In [7]:
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

In [10]:
class MLP(nn.Module):
  def __init__(self):
    super().__init__()
    self.hidden = nn.Linear(20, 256)
    self.output = nn.Linear(256, 10)
  
  def forward(self, x):
    return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size = (2, 20))
Y = net(X)

In [11]:
torch.save(net.state_dict(), 'mlp.params')

In [12]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])

In [14]:
net.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [17]:
params = torch.load('mlp.params')
params

OrderedDict([('hidden.weight',
              tensor([[-0.0549,  0.0475, -0.2009,  ...,  0.0862,  0.0622,  0.1051],
                      [-0.1787,  0.2103,  0.0194,  ...,  0.0188, -0.0090, -0.1018],
                      [-0.1298, -0.1686,  0.1571,  ...,  0.0102,  0.0005, -0.2098],
                      ...,
                      [ 0.0916,  0.1321,  0.2020,  ...,  0.0916,  0.1629,  0.1672],
                      [-0.1786, -0.1479,  0.0518,  ...,  0.1772, -0.0902, -0.0542],
                      [-0.1695, -0.1135, -0.2144,  ..., -0.0015,  0.1899,  0.1426]])),
             ('hidden.bias',
              tensor([ 0.0476, -0.2103, -0.2079, -0.0552,  0.0300,  0.1361, -0.1339,  0.1257,
                       0.0017, -0.0353, -0.1388, -0.1875,  0.0138, -0.0793, -0.2206, -0.1492,
                      -0.0414, -0.1647,  0.0103,  0.1937, -0.0946,  0.0573, -0.0485, -0.1692,
                       0.0177, -0.1595,  0.2102,  0.0609,  0.0835, -0.0034, -0.0236, -0.0156,
                       0.1666,

In [20]:
type(params)

collections.OrderedDict