<a href="https://colab.research.google.com/github/VirtueZhao/Dive_into_Deep_Learning/blob/main/6_4_Multiple_Input_and_Multiple_Output_Channels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import d2l
import torch

def corr2d_multi_in(X, K):
  
  return sum(d2l.corr2d(x, k) for x, k in zip(X,K))

In [8]:
X = torch.tensor([
      [[0.0,1.0,2.0], [3.0,4.0,5.0], [6.0,7.0,8.0]],
      [[1.0,2.0,3.0], [4.0,5.0,6.0], [7.0,8.0,9.0]]])
K = torch.tensor([
      [[0.0,1.0], [2.0,3.0]],
      [[1.0,2.0], [3.0,4.0]]])

print(X.shape)
print(K.shape)

corr2d_multi_in(X, K)

torch.Size([2, 3, 3])
torch.Size([2, 2, 2])


tensor([[ 56.,  72.],
        [104., 120.]])

In [14]:
z = zip(X, K)
for x, k in z:
  print("x: ", x)
  print("k: ", k)
  print()

x:  tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
k:  tensor([[0., 1.],
        [2., 3.]])

x:  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
k:  tensor([[1., 2.],
        [3., 4.]])



In [21]:
def corr2d_multi_in_out(X, K):
  return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

K = torch.tensor([
      [[0.0,1.0], [2.0,3.0]],
      [[1.0,2.0], [3.0,4.0]]])
# print(K)
print(K.shape)
K = torch.stack((K, K+1, K+2),0)
# print(K)
print(K.shape)
print(len(K))

torch.Size([2, 2, 2])
torch.Size([3, 2, 2, 2])
3


In [22]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [42]:
def corr2d_multi_in_out_1x1(X, K):
  print("X Shape before Reshape: ", X.shape)
  print("K Shape bfore Reshape: ", K.shape)
  # print(X)
  print(K)
  c_i, h, w = X.shape
  # print("C_i: ", c_i)
  # print("h: ", h)
  # print("w: ", w)
  c_o = K.shape[0]
  X = X.reshape((c_i, h * w))
  K = K.reshape((c_o, c_i))
  print("X Shape After Reshape: ", X.shape)
  # print(X)
  print("K Shape After Reshape: ", K.shape)
  # print(K)

  Y = torch.matmul(K, X)
  print("T Shape before Reshape: ", Y.shape)
  Y = Y.reshape((c_o, h, w))
  print("T Shape After Reshape: ", Y.shape)
  return Y

X = torch.normal(0,1,(3,3,3))
K = torch.normal(0,1,(2,3,1,1))

Y1 = corr2d_multi_in_out_1x1(X, K)

X Shape before Reshape:  torch.Size([3, 3, 3])
K Shape bfore Reshape:  torch.Size([2, 3, 1, 1])
tensor([[[[-0.8008]],

         [[-0.0861]],

         [[ 1.0265]]],


        [[[-0.3049]],

         [[ 0.1935]],

         [[-0.4183]]]])
X Shape After Reshape:  torch.Size([3, 9])
K Shape After Reshape:  torch.Size([2, 3])
T Shape before Reshape:  torch.Size([2, 9])
T Shape After Reshape:  torch.Size([2, 3, 3])


In [41]:
X = torch.normal(0,1,(3,3,3))
K = torch.normal(0,1,(2,3,1,1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

assert float(torch.abs(Y1-Y2).sum()) < 1e-6
print(float(torch.abs(Y1-Y2).sum()) < 1e-6)

X Shape before Reshape:  torch.Size([3, 3, 3])
K Shape bfore Reshape:  torch.Size([2, 3, 1, 1])
X Shape After Reshape:  torch.Size([3, 9])
K Shape After Reshape:  torch.Size([2, 3])
T Shape before Reshape:  torch.Size([2, 9])
T Shape After Reshape:  torch.Size([2, 3, 3])
True
